service: Test
provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-west-1
  memorySize: 128
functions:
app:
handler: handler
events:
- http:
    path: /hello
    method: ANY
    cors: true
