service: serverless-tutorial-rds
plugins:
  - serverless-offline    
provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 128
  timeout: 30
  region: us-west-1
functions:

  getAllTodos:
    handler: handler.getAllTodos
    events:
      - http:
          path: /todo
          method: get
          cors: true
  